version: "3.8"

services:
    postgres:
        image: postgres:16
        container_name: shortener_postgres_db
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-admin}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-adminpassword}
            POSTGRES_DB: ${POSTGRES_DB:-shorten_db}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:7
        container_name: shortener_redis_cache
        command: redis-server --requirepass ${REDIS_PASSWORD:-redispassword}
        restart: unless-stopped
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD:-redispassword}
        ports:
            - "6379:6379"

volumes:
    postgres_data:
